import subprocess #line:1:import subprocess
import base64 #line:2:import base64
from hashlib import sha256 #line:3:from hashlib import sha256
def ec (OOOOO0O0OO0OOO000 ):#line:5:def ec(text):
    return sha256 (OOOOO0O0OO0OOO000 .encode ("ascii")).hexdigest ()#line:6:return sha256(text.encode("ascii")).hexdigest()
current_machine_id =str (subprocess .check_output ('wmic csproduct get uuid'),'utf-8').split ('\n')[1 ].strip ()#line:8:current_machine_id = str(subprocess.check_output('wmic csproduct get uuid'), 'utf-8').split('\n')[1].strip()
message =current_machine_id #line:10:message = current_machine_id
message_bytes =message .encode ('ascii')#line:11:message_bytes = message.encode('ascii')
base64_bytes =base64 .b64encode (message_bytes )#line:12:base64_bytes = base64.b64encode(message_bytes)
base64_message =base64_bytes .decode ('ascii')#line:13:base64_message = base64_bytes.decode('ascii')
print ("[+] ------------------------------------------------------------------------- [+]")#line:15:print("[+] ------------------------------------------------------------------------- [+]")
print ("                                   ")#line:16:print("                                   ")
print ("                                   ")#line:17:print("                                   ")
print ("                                   ")#line:18:print("                                   ")
print ("                                   ")#line:19:print("                                   ")
print ("                                   ")#line:20:print("                                   ")
print ("                                   ")#line:21:print("                                   ")
print ("                                   ")#line:22:print("                                   ")
print ("                                   ")#line:23:print("                                   ")
print ("                                   ")#line:24:print("                                   ")
print ("                                   ")#line:25:print("                                   ")
print ("                                   ")#line:26:print("                                   ")
print ("                        NT MACHINES ONLY          ")#line:27:print("                        NT MACHINES ONLY          ")
print ("                                   ")#line:28:print("                                   ")
print (f"SHA256 -> {ec(current_machine_id)}")#line:29:print(                      f"SHA256 -> {ec(current_machine_id)}")
print (f"Base64 -> {base64_message}")#line:30:print(                          f"Base64 -> {base64_message}")
print (f"Normal -> {current_machine_id}")#line:31:print(                        f"Normal -> {current_machine_id}")
print ("                                   ")#line:32:print("                                   ")
print ("                                   ")#line:33:print("                                   ")
print ("                        NT MACHINES ONLY          ")#line:34:print("                        NT MACHINES ONLY          ")
print ("                                   ")#line:35:print("                                   ")
print ("                                   ")#line:36:print("                                   ")
print ("                                   ")#line:37:print("                                   ")
print ("                                   ")#line:38:print("                                   ")
print ("                                   ")#line:39:print("                                   ")
print ("                                   ")#line:40:print("                                   ")
print ("                                   ")#line:41:print("                                   ")
print ("[+] -------------------------------------------------------------------------- [+]")#line:42:print("[+] -------------------------------------------------------------------------- [+]")
